version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=devarshi
      - POSTGRES_PASSWORD=eA234123Pq
      - POSTGRES_DB=supreme_org
    ports:
      - "5432:5432"
    volumes:
      - hero_org_vol:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=devarshitrivedi000001@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=eA#2Pbqa@23121
    ports:
      - "8080:80"

volumes:
  hero_org_vol: